### ISSUE TITLE
建议加一个无temp文件夹时自动新建功能

### ISSUE THREAD

**Issue by devil233-ui** [GangFaDeShenMe/yunzai-yt-dl-plugin#2]
如图，因为我会定期清理这个文件夹，所以插件就找不到在哪创建文件了
![Image_1732301749706](https://github.com/user-attachments/assets/7933e367-e01e-41e3-9be2-d13eae36cfc6)
手动新建temp后可以正常解析

**Comment by Foxerine** [comment]
已新增，readme过会更新
