### ISSUE TITLE
海外服务器提示Proxy opts.uri is mandatory

### ISSUE THREAD

**Issue by devil233-ui** [GangFaDeShenMe/yunzai-yt-dl-plugin#3]
![image](https://github.com/user-attachments/assets/20418ddd-d719-43fa-929f-c400170333a5)
另外我看config.json是空的，是不是可以加点配置项？比如确认网络环境啥的

**Comment by Foxerine** [comment]
感谢指出，已修正

**Comment by devil233-ui** [comment]
不知道为啥突然没法更新了

> 远程仓库连接错误：https://github.com/GangFaDeShenMe/yunzai-yt-dl-plugin.git/

重装也不行
![image](https://github.com/user-attachments/assets/0741cf5c-c180-472a-aa16-438f39fee2a8)

**Comment by devil233-ui** [comment]
辛苦辛苦，居然还开了nb分支
