### ISSUE TITLE
指令更新似乎有问题

### ISSUE THREAD

**Issue by devil233-ui** [GangFaDeShenMe/yunzai-yt-dl-plugin#5]
pnpm i这步不知道为什么无法进行，在进行#全部更新 时还会阻塞其他插件更新
![9f2515abc9e7a2ba684182c2dcf417eb](https://github.com/user-attachments/assets/71374d95-fc76-4936-ac11-10d76f9f241c)
![image](https://github.com/user-attachments/assets/2ef81541-bfc8-4bbc-9444-8400de191b58)
![17eaf8b7711ea31daf1b1a6304a61afd_720](https://github.com/user-attachments/assets/070bf321-ac98-447b-b7d5-a96213c27956)

**Comment by Foxerine** [comment]
试试在bot根目录的命令行界面执行 pnpm i，而不是直接在yunzai bot内部的命令执行pnpm i
![QQ_1734280368152](https://github.com/user-attachments/assets/0d566af7-cba9-42b0-bc1a-9a1e1169dea3)

**Comment by devil233-ui** [comment]
不是，pnpm i不是我执行的，是bot自己的。

GangFaDeShenMe ***@***.***> 于 2024年12月16日周一 00:33写道：

**Comment by devil233-ui** [comment]
cli是可以执行没错，问题在于我一但进行全部插件更新到了yt这里就会被卡住233

devil ***@***.***> 于 2024年12月16日周一 00:34写道：

**Comment by Foxerine** [comment]
我尝试了好几次，似乎都无法重现？我按照如下的步骤试图手动模拟旧版本更新：
1. 在插件目录删除最新版本更新的依赖 youtubei.js `pnpm remove youtubei.js`
![QQ_1734282454926](https://github.com/user-attachments/assets/d7d3be2d-1ffb-48b2-bfee-0a49578ea84d)

2. 手动安装之前版本的依赖 `pnpm add youtubei.js@^10.5.0`
![QQ_1734282487662](https://github.com/user-attachments/assets/731e8621-4b3e-48c6-b330-e9762ed0d695)

3. 确保当前的插件装的是最新版本 `git fetch origin` `git pull origin master`
![QQ_1734282664822](https://github.com/user-attachments/assets/8399a039-5e5f-4785-802b-a5ebedd96a20)

4. 在插件根目录执行`git reset --hard HEAD^`，回退到上一个版本
![QQ_1734282706700](https://github.com/user-attachments/assets/7418daa3-68a6-40d8-a82d-f975854e4044)

5. 为了模拟海外服务器，挂上代理并启动bot `proxychians node app` 
![QQ_1734282782908](https://github.com/user-attachments/assets/2128de78-d206-4c48-a523-fa90c97c5949)

6. 进行更新 `#全部更新`
![QQ_1734282814804](https://github.com/user-attachments/assets/23d21101-6c81-416b-b4dd-2904dd935b1f)
![QQ_1734282867276](https://github.com/user-attachments/assets/30bc7658-73a2-433a-960a-c83fcfa88d22)
![QQ_1734283019486](https://github.com/user-attachments/assets/b4d7d07b-c3fc-46d8-beea-0a5a017c8990)
![QQ_1734283055620](https://github.com/user-attachments/assets/71f6dcd6-943e-476f-83c8-ec1be360b4de)
![QQ_1734283255610](https://github.com/user-attachments/assets/066eeed9-1770-4822-ba10-f48bb9aeb78a)
pnpm install 正常执行

7. 插件正常工作
![QQ_1734283321968](https://github.com/user-attachments/assets/de0b2325-e7f3-4596-ab40-1059eff7c4b2)

我使用arch linux wsl, TRSS-Yunzai v3.1.3, pnpm 9.11.0, nodejs v22.9.0

**Comment by Foxerine** [comment]
如果能辛苦详细描述一下你那边是怎么重现这个问题的，提供一些版本之类的信息，就更好了，我明天白天来研究一下

**Comment by devil233-ui** [comment]
我跟着您的流程走了一圈可以复现
![image](https://github.com/user-attachments/assets/f61e150a-d6e8-466a-9b33-b04fa839ca70)
![image](https://github.com/user-attachments/assets/ba532821-98b7-4611-9202-4acb0635d073)

一些信息：
> 乌班图22
> bot采用[容器](https://trss.me/)安装运行
> trss为[最新版](https://gitee.com/TimeRainStarSky/Yunzai/commit/69726d2a03baaf40a774520b4c7b5f4e724fce39)
> [root@TRSS-AllBot TRSS_AllBot]# node -v
> v23.1.0
> [root@TRSS-AllBot TRSS_AllBot]# pnpm -v
> 9.12.3
容器外的感觉没啥意义
> ~~root@VM-12-10-ubuntu:/TRSS_AllBot/TRSS-Yunzai/plugins/yunzai-yt-dl-plugin# node -v
> v20.18.0
> root@VM-12-10-ubuntu:/TRSS_AllBot/TRSS-Yunzai/plugins/yunzai-yt-dl-plugin# pnpm -v
> 9.13.2~~

我现在用的是国内环境了（您不需要模拟），pnpm也有设置镜像源
![image](https://github.com/user-attachments/assets/7c938800-d850-47fd-887b-28fe42504fcf)
而且cli可以pnpm成功的话肯定不是这问题了
![image](https://github.com/user-attachments/assets/e35c6e13-772c-4ddb-8daa-5ca72da1d78d)

**Comment by devil233-ui** [comment]
大概能定位问题了，容器内外的store来源不同？
![image](https://github.com/user-attachments/assets/196e0658-c1d8-47ad-9aec-0f570dffe04d)
容器内无法更新容器外的依赖，且崽的控制台无法提供
> The modules directories will be removed and reinstalled from scratch. Proceed? 

这一步的操作可选项，也没有默认执行动作。

反之容器外无法移除容器内安装的依赖
![image](https://github.com/user-attachments/assets/e0f2d445-a4a5-4879-91b2-483b4d17f58a)

**Comment by devil233-ui** [comment]
但是我无论在容器内还是容器外建立store，指令更新依然会卡住……放弃研究了

**Comment by Foxerine** [comment]
可以用这段代码临时代替一下 `yunzai根目录/lib/bot.js` 中的 `exec` 方法，我这里是536-553行，记得先做好备份，以便看到命令执行的实时输出

```
async exec(cmd, opts = {}) {
  const { spawn } = await import('node:child_process')
  return new Promise((resolve, reject) => {
    const name = logger.cyan(this.String(cmd))
    this.makeLog(opts.quiet ? "debug" : "mark", name, "Command")
	let stdoutFull = Buffer.from('')
    let stderrFull = Buffer.from('')
    const start_time = Date.now()

    const args = Array.isArray(cmd) ? [...cmd] : cmd.split(/\s+/)
    const command = Array.isArray(cmd) ? args.shift() : args.shift()
    
    const child = spawn(command, args, {
      ...opts,
      shell: !Array.isArray(cmd)
    })

    child.stdout.on('data', (data) => {
      stdoutFull = Buffer.concat([stdoutFull, data])
      const output = data.toString().trim()
      if (output) {
        this.makeLog(
          opts.quiet ? "debug" : "mark",
          `${name} ${logger.green('[实时输出]')}\n${output}`,
          "Command"
        )
      }
    })

    child.stderr.on('data', (data) => {
      stderrFull = Buffer.concat([stderrFull, data])
      const error = data.toString().trim()
      if (error) {
        this.makeLog(
          opts.quiet ? "debug" : "error",
          `${name} ${logger.red('[错误输出]')}\n${error}`,
          "Command"
        )
      }
    })

    child.on('close', (code) => {
      const stdout = stdoutFull.toString().trim()
      const stderr = stderrFull.toString().trim()
      this.makeLog(
        opts.quiet ? "debug" : "mark",
        `${name} ${logger.green(`[完成${this.getTimeDiff(start_time)}]`)} ${code === 0 ? '' : logger.red(`[退出码: ${code}]`)}`,
        "Command"
      )

      resolve({
        error: code === 0 ? null : new Error(`Command failed with exit code ${code}`),
        stdout,
        stderr,
        raw: {
          stdout: stdoutFull,
          stderr: stderrFull
        }
      })
    })

    child.on('error', (error) => {
      this.makeLog(opts.quiet ? "debug" : "error", error, "Command")
      reject(error)
    })
  })
}
```

然后再尝试更新一下，看下pnpm install 的输出是卡在哪里了

![QQ_1734336896861](https://github.com/user-attachments/assets/f73cb82e-0be9-4a48-8767-4d28036131c6)

**Comment by devil233-ui** [comment]
~~猜对了一半~~
![image](https://github.com/user-attachments/assets/778bad36-93ea-4a83-8a27-a9d558c86210)

**Comment by devil233-ui** [comment]
我在其他插件从未碰到过类似问题，所以可能要麻烦您参考下别人是怎么写的了

**Comment by Foxerine** [comment]
我特意在海外的服务器上搭建了一个全新的容器化的yunzai，按照之前所述的方法重现，仍然无法重现你提到的问题
![QQ_1734345302074](https://github.com/user-attachments/assets/f40324dc-9e23-4192-a663-e36928d4c37c)

这个问题应该与插件本身的实现无关，我之前都没有注意到你在容器内外都进行了操作~~为什么会有人进行这种操作~~猜测可能与你之前不小心混用了容器内外的pnpm有关，这可能造成路径上的混乱
![QQ_1734342771805](https://github.com/user-attachments/assets/902662a1-92a3-4bb8-8947-d417aa700e4d)

我尝试模拟你可能的操作：
1. 挂载yunzai到host：`docker run -v /root/TRSS_Yunzai:/root/TRSS_Yunzai trss:allbot /bin/bash`
2. 尝试用容器外的pnpm进行install
![QQ_1734346727491](https://github.com/user-attachments/assets/e13c36eb-ec3c-4d5f-8113-a72e953097b1)
3. 然后使用pnpm试图进行修改依赖
![QQ_1734346781323](https://github.com/user-attachments/assets/0edac3cd-6ea1-4525-b2ba-d0d8591ab4ea)
![QQ_1734347098718](https://github.com/user-attachments/assets/24bc6af9-d878-4c21-b47c-14cafe3c4aff)
（卡住了）

可以看见，重现了你的问题，所以问题的核心确定了在于你混用了容器内外的pnpm。
那么，你可以在容器内，用这个指令重设 store dir: `pnpm config set store-dir  /root/.local/share/pnpm/store/v3 --global`
![QQ_1734346969883](https://github.com/user-attachments/assets/008c04ff-5040-46b3-a6c9-7aad2db20b72)
然后尝试安装 `#全部更新`
![QQ_1734347297396](https://github.com/user-attachments/assets/05462d25-39b9-42a0-beec-cd12c5cb101c)

这样应该解决了问题

至于别人的写法，[更新](https://github.com/GangFaDeShenMe/yunzai-yt-dl-plugin/commit/d0f118b35449e0bcef563c1e64c0ee724a39dfdb)实质上只是修改了一个依赖的版本号而已，这与[别人的实现](https://github.com/XasYer/steam-plugin/commit/6c488700a482803b9bb86da0f145fb9dd6d8ca6d)和 [别人的实现](https://github.com/yuanplussfive/y-tian-plugin/commit/2cd8729f5fc4d2768f444a768a805c4f81882db7)没有什么区别。

鉴于多种环境都无法重现，先关闭这个issue as can't reproduce了，有后续问题可以直接在这里继续comment

**Comment by Foxerine** [comment]
至于为啥别人的插件都没问题，可能是因为你在host操作pnpm到现在，它们都没更新过依赖，我正好在这段时间更新了依赖，所有就卡我这了

**Comment by devil233-ui** [comment]
不是，所谓host操作（如果我理解没错就是指容器内外测试那点？），是我昨晚尝试定位问题时才第一次执行的

如果说这段时间我曾经干过啥特殊的：
1.我和人吐槽说有时pnpm会掉依赖的事别人给我建议删掉pnpm锁.....
2.进容器装过python依赖（这会影响node么），除此之外所有指令都是容器外执行

emmm坏消息，在容器内重设 store dir并不能解决这个问题

**Comment by devil233-ui** [comment]
现在尝试重装根目录的整个node module

**Comment by Foxerine** [comment]
哈哈哈，看来真的是玄学，不能重现我也不知道了

**Comment by Foxerine** [comment]
你提到“除此之外所有指令都是容器外执行”，有关pnpm的指令最好全部在容器内执行，因为`#全部更新`之类的本质上就是在容器内执行pnpm install，如果你把容器的yunzai挂载到容器外，然后在容器外(host)执行pnpm指令，会造成混乱
你可以在容器环境内，yunzai bot目录/node_modules/.modules.yaml翻到最后面，看看`storeDir`是哪里，然后容器内指定store dir到这里，如果重装之后还不行的话

**Comment by devil233-ui** [comment]
> 看看storeDir是哪里，然后容器内指定store dir到这里，如果重装之后还不行的话

![image](https://github.com/user-attachments/assets/018a9a9a-d1e7-4657-9053-5de027f4e2c4)
终于解决了！！！
感激不尽，明明不是插件问题还这么尽心尽力，真的，非常。

**Comment by Foxerine** [comment]
没事，举手之劳，能帮到你就是最好的，我是python/c++出身的，也当学习探究pnpm的原理了哈哈
